DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS books;


CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    username VARCHAR(40) NOT NULL,
    email VARCHAR(40) NOT NULL UNIQUE,
    password VARCHAR(40) NOT NULL
);

CREATE TABLE books(
    id SERIAL PRIMARY KEY,
    isbn VARCHAR(40) NOT NULL UNIQUE,
    title VARCHAR(40) NOT NULL,
    author VARCHAR(40) NOT NULL,
    year TIMESTAMP NOT NULL
);

CREATE TABLE reviews(
    id SERIAL PRIMARY KEY,
    userId SERIAL NOT NULL UNIQUE REFERENCES users (id),
    bookId SERIAL NOT NULL REFERENCES books (id),
    total_rating INTEGER DEFAULT 0,
    avg_rating INTEGER DEFAULT 0,
    reviewedAt TIMESTAMP NOT NULL
);
